name: oreaderdev
dependencies:
    - python=3.6.2
    - nose
    - sqlalchemy
    - pandas
    - pip:
        - toolz
        - infinity
        - names
        - interval
        - frozendict==1.2
        - arrow
        - git+https://github.com/jcrudy/cyinterval.git

