name: oreaderdev
dependencies:
    - python=3.6.2
    - nose
    - sqlalchemy
    - pandas
    - pip:
        - toolz
        - sqlalchemy==1.3.13
        - infinity
        - names
        - interval
        - arrow
        - git+https://github.com/jcrudy/cyinterval.git
        - git+https://github.com/mattlewissf/mfrozendict.git

